# Configuration for the embedding model used in vector generation
embedding:
  # Embeddings convert a single text into a numerical vector that captures its semantic meaning.
  # These vectors are compared to measure similarity between query and documents.
  model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  transformers_inference_api: 'http://172.20.64.1:5000' # 'http://192.168.1.9:5000'  #'http://172.20.64.1:5000'

reranking:
  # Reranking works on pairs of texts (query, document).
  # It scores how relevant each document is to the query, and reorders the results accordingly.
  model: BAAI/bge-reranker-base
  reranker_inference_api: 'http://172.20.64.1:5000' #'http://192.168.1.9:5000' #'http://172.20.64.1:5000'

loading:
  input_folder: "../data/input_documents/"
  output_folder: "../data/output_documents/"
  files:
    - docx

chunking:
  strategies:
#    - name: fixed_size
#      min_size: 135               # Number of tokens per chunk

#    - name: overlapping
#      min_size: 135            # Maximum number of tokens per chunk
 #     overlap: 10%             # Number of characters that overlap between chunks

    - name: hierarchical
      num_tokens: 256         # Maximum tokens per chunk

  blacklist_chapters: # Not case sensitive
    - "Storia delle Revisioni"
    - "Contatti"
    - "Indice"
    - "Table of Contents"
    - "Sommario"
    - "Version History"

# Configuration for the vector database
vector_database:
  port: 8081
  collection_name_suffix: sigma_docs   # Name of the collection within the vector database
  search_strategies:
    - semantic:
        top_k: 5
    - keyword:
        top_k: 5
    - hybrid:
        alpha : 0.6
        top_k: 5

evaluation:
  dataset_path: "../data/MrWolf_datasetdomande_IngMan.xlsm"
  report_path: "../../report"





